### ISSUE TITLE
Error formatting document in Windows 10 and prettier-plugin-apex@1.10.0

### ISSUE THREAD

**Issue by cleilson-oliveira-osf** [dangmai/prettier-plugin-apex#656]
Hi there, I hope everything is going well!

I keep getting this error **Error formatting document**, when I'm using the VS Code extension. The total output is just bellow. This error happens with every Apex class.

```Shell
["INFO" - 2:56:33 PM] Extension Name: esbenp.prettier-vscode.
["INFO" - 2:56:33 PM] Extension Version: 9.9.0.
["INFO" - 3:08:59 PM] Formatting file:///.../project-root-folder/force-app/main/default/classes/CategoryWrapper.cls
["INFO" - 3:08:59 PM] Using config file at '...\project-root-folder\.prettierrc'
["INFO" - 3:08:59 PM] Using ignore file (if present) at ...\project-root-folder\.prettierignore
["INFO" - 3:08:59 PM] File Info:
{
  "ignored": false,
  "inferredParser": "apex"
}
["INFO" - 3:08:59 PM] Detected local configuration (i.e. .prettierrc or .editorconfig), VS Code configuration will not be used
["INFO" - 3:08:59 PM] Prettier Options:
{
  "filepath": "...\\project-root-folder\\force-app\\main\\default\\classes\\CategoryWrapper.cls",
  "parser": "apex",
  "tabWidth": 4,
  "printWidth": 120,
  "endOfLine": "lf",
  "trailingComma": "none",
  "apexInsertFinalNewline": false
}
["ERROR" - 3:09:00 PM] Error formatting document.
Error: 
    at parseTextWithSpawn (...\project-root-folder\node_modules\prettier-plugin-apex\src\parser.js:36:11)
    at Object.parse (...\project-root-folder\node_modules\prettier-plugin-apex\src\parser.js:497:21)
    at Object.parse (...\project-root-folder\node_modules\prettier\index.js:7361:23)
    at coreFormat (...\project-root-folder\node_modules\prettier\index.js:8672:18)
    at formatWithCursor2 (...\project-root-folder\node_modules\prettier\index.js:8864:18)
    at ...\project-root-folder\node_modules\prettier\index.js:39174:12
    at Object.format (...\project-root-folder\node_modules\prettier\index.js:39188:12)
    at t.default.format (...\.vscode\extensions\esbenp.prettier-vscode-9.9.0\dist\extension.js:1:14565)
    at t.PrettierEditProvider.provideEdits (...\.vscode\extensions\esbenp.prettier-vscode-9.9.0\dist\extension.js:1:11259)
    at $.provideDocumentFormattingEdits (...\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:87:45865)
["INFO" - 3:09:00 PM] Formatting completed in 225ms.
```

More info about the environment:

**JDK version** (from the project root folder):
```Shell
$ java --version
openjdk 11.0.16.1 2022-07-19 LTS
OpenJDK Runtime Environment Zulu11.58+23-CA (build 11.0.16.1+1-LTS)
OpenJDK 64-Bit Server VM Zulu11.58+23-CA (build 11.0.16.1+1-LTS, mixed mode)
```

**NodeJS version** (from the project root folder):
```Shell
$ node --version
v14.17.6
```

**NPM version** (from the project root folder):
```Shell
$ npm --version
8.6.0
```

**Prettier version** (from the project root folder):
```Shell
$ npm ls prettier
project-name@1.0.0 ...\project-root-folder
+-- @prettier/plugin-xml@2.2.0
| `-- prettier@2.6.2 deduped
+-- prettier-plugin-apex@1.10.0
| `-- prettier@2.6.2 deduped
`-- prettier@2.6.2
```

**This is the part of my `package.json` file:**
```JSON
  "devDependencies": {
    "@lwc/eslint-plugin-lwc": "^1.1.2",
    "@prettier/plugin-xml": "^2.0.1",
    "@salesforce/eslint-config-lwc": "^3.2.3",
    "@salesforce/eslint-plugin-aura": "^2.0.0",
    "@salesforce/eslint-plugin-lightning": "^1.0.0",
    "@salesforce/sfdx-lwc-jest": "^1.1.0",
    "eslint": "^8.11.0",
    "eslint-plugin-import": "^2.25.4",
    "eslint-plugin-jest": "^26.1.2",
    "husky": "^7.0.4",
    "lint-staged": "^12.3.7",
    "prettier": "^2.6.0",
    "prettier-plugin-apex": "^1.10.0"
  }
```

And I face the same error when I execute the `prettier` formatter by the command line (from the project root folder):
```Shell
$ npx prettier force-app\main\default\classes\CategoryWrapper.cls
force-app\main\default\classes\CategoryWrapper.cls[error] force-app\main\default\classes\CategoryWrapper.cls: Error
[error]     at parseTextWithSpawn (...\project-root-folder\node_modules\prettier-plugin-apex\src\parser.js:36:11)
[error]     at Object.parse (...\project-root-folder\node_modules\prettier-plugin-apex\src\parser.js:497:21)
[error]     at Object.parse (...\project-root-folder\node_modules\prettier\index.js:7361:23)
[error]     at coreFormat (...\project-root-folder\node_modules\prettier\index.js:8672:18)
[error]     at formatWithCursor2 (...\project-root-folder\node_modules\prettier\index.js:8864:18)
[error]     at Object.formatWithCursor (...\project-root-folder\node_modules\prettier\index.js:39174:12)
[error]     at format (...\project-root-folder\node_modules\prettier\cli.js:12043:24)
[error]     at formatFiles2 (...\project-root-folder\node_modules\prettier\cli.js:12122:20)
[error]     at async main (...\project-root-folder\node_modules\prettier\cli.js:12327:5)
[error]     at async Object.run (...\project-root-folder\node_modules\prettier\cli.js:12274:5)
```

**Comment by dangmai** [comment]
Hi,

Thanks for using my library. Just as a sanity check, does this happen to all files or just `CategoryWrapper.cls`? Can you double check that `CategoryWrapper.cls` is valid Apex, and that it can be deployed to Salesforce?

**Comment by cleilson-oliveira-osf** [comment]
Hi @dangmai,

First of all, this is very good plugin, thanks a lot to create and maintain.

This error happens to all apex files. They are valid APEX classes due I could deploy all of them to Salesforce.
I used the `CategoryWrapper.cls` file just to give an example.

**Comment by dangmai** [comment]
If possible, could you provide the path to your project? I just fixed this issue yesterday https://github.com/dangmai/prettier-plugin-apex/issues/645 that has to do with path length limit in Windows, and you may be running into the same thing. If that's the case then it will be fixed in the next version, but in the mean time you can try tweaking Windows settings to see if it helps: https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=registry

**Comment by cleilson-oliveira-osf** [comment]
I had already applied the settings described in https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=registry before to create the issue, and the problem was still happening.

But I've moved the project root folder in order to have a minor full path, and now, I can use the plugin without problems.

Thanks a lot.
